label var isco08_c         "4-digit ISCO 08 classification, current job"
label var isco08_l         "4-digit ISCO 08 classification, past job"
label var isco2c           "2-digit ISCO 08 classification, current job"
label var isco2l           "2-digit ISCO 08 classification, past job"
label var isic2c           "2-digit ISIC rev 4 classification, current job"
label var isic2l           "2-digit ISIC rev 4 classification, past job"   
label var spfwt0           "Final full sample weight"
label var earnhrbonusppp   "Hourly earnings including bonuses for wage and salary earners, PPP corrected $US (derived)"
label var edwork           "Interaction between adults' work and education status (derived)"
label var d_q05a2          "Current work - Start of work for employer - Year"
label var d_q10_c          "Current work - Hours/week (top-coded at 60)"
label var d_q10            "Current work - Hours/week"
label var ictwork_wle_ca   "Index of use of ICT skills at work, categorised WLE (derived)"
label var icthome_wle_ca   "Index of use of ICT skills at home, categorised WLE (derived)"
label var c_d05            "Current status/work history - Employment status (DERIVED BY CAPI)"
label var edcat6           "Highest level of formal education obtained (6 categories - derived)"
label var edcat7           "Highest level of formal education obtained (7 categories - derived)"
label var edcat8           "Highest level of formal education obtained (8 categories - derived)"
label var edlevel3		   "Educational level of the respondent (DERIVED BY CAPI)"	
label var age_r            "Person resolved age from BQ and QC check (derived)"
label var b_q01b           "Education - Highest qualification - Area of study"
label var vet              "Respondent's highest level of education obtained is vocationally oriented (derived, ISCED3 and 4 only)"
label var gender_r         "Person resolved gender from BQ and QC check (derived)"
label var c_q09_c          "Current status/work history - Years of paid work during lifetime (top-coded at 47)"
label var f_q06c           "Skill use work - How often - Using hands or fingers"
label var f_q05a           "Skill use work - Problem solving - Simple problems"
label var f_q05b           "Skill use work - Problem solving - Complex problems"
label var g_q03g           "Skill use work - Numeracy - How often - Use simple algebra or formulas"
label var g_q03h           "Skill use work - Numeracy - How often - Use advanced math or statistics"
label var f_q02b           "Skill use work - How often - Teaching people"
label var f_q03b           "Skill use work - How often - Planning others activities"
label var f_q04a           "Skill use work - How often - Influencing people"
label var f_q04b           "Skill use work - How often - Negotiating"
label var f_q02d           "Skill use work - How often - Selling"
label var f_q02e           "Skill use work - How often - Advising people"
label var f_q01b           "Skill use work - Time cooperating with co-workers"
label var f_q02a           "Skill use work - How often - Sharing work-related info"
label var ageg5lfs         "Age groups in 5-year intervals based on LFS groupings (derived)'


